# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies without running lifecycle scripts
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Production stage
FROM node:lts-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# Copy built artifacts and package definition
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./
COPY --from=builder /app/package-lock.json ./

# Install only production dependencies
RUN npm install --production --ignore-scripts

# Default command to start the MCP server
ENTRYPOINT ["node", "dist/main.js"]
